export default {
    fetchLines:'FETCH_LINES',
    fetchLinesSuccess:'FETCH_LINES_SUCCESS',
    createLine:'CREATE_LINE',
    createLineSuccess:'CREATE_LINE_SUCCESS',
    createLineFailed:'CREATE_LINE_FAILED',
    updateLine:'UPDATE_LINE',
    updateLineSuccess:'UPDATE_LINE_SUCCESS',
    updateLineFailed:'UPDATE_LINE_FAILED',
    deleteLine:'DELETE_LINE',
    deleteLineSuccess:'DELETE_LINE_SUCCESS',
    deleteLineFailed:'DELETE_LINE_FAILED',

    fetchStations:'FETCH_STATIONS',
    fetchStationsSuccess:'FETCH_STATIONS_SUCCESS',
    addStation:'ADD_STATION',
    addStationSuccess:'ADD_STATION_SUCCESS',
    addStationFailed:'ADD_STATION_FAILED',
    updateStationKey:'UPDATE_STATION_KEY',
    updateStationKeySuccess:'UPDATE_STATION_KEY_SUCCESS',
    updateStationKeyFailed:'UPDATE_STATION_KEY_FAILED',
    deleteStation:'DELETE_STATION',
    deleteStationSuccess:'DELETE_STATION_SUCCESS',
    deleteStationFailed:'DELETE_STATION_FAILED'
}