export default{
    fetchOrgs: 'FETCH_ORGS',
    fetchOrgsSuccess: 'FETCH_ORGS_SUCCESS',
    fetchOrgsFailed: 'FETCH_ORGS_FAILED',
    createOrg: 'CREATE_ORG',
    createOrgSuccess: 'CREATE_ORG_SUCCESS',
    createOrgFailed: 'CREATE_ORG_FAILED',
    updateOrg: 'UPDATE_ORG',
    updateOrgSuccess: 'UPDATE_ORG_SUCCESS',
    updateOrgFailed: 'UPDATE_ORG_FAILED',
    deleteOrg: 'DELETE_ORG',
    deleteOrgSuccess: 'DELETE_ORG_SUCCESS',
    deleteOrgFailed: 'DELETE_ORG_FAILED',

    fetchAccounts: 'FETCH_ACCOUNTS',
    fetchAccountsSuccess: 'FETCH_ACCOUNTS_SUCCESS',
    fetchAccountsFailed: 'FETCH_ACCOUNTS_FAILED',
    createAccount: 'CREATE_ACCOUNT',
    createAccountSuccess: 'CREATE_ACCOUNTS_SUCCESS',
    createAccountFailed: 'CREATE_ACCOUNTS_FAILED',
    updateAccount: 'UPDATE_ACCOUNTS',
    updateAccountSuccess: 'UPDATE_ACCOUNTS_SUCCESS',
    updateAccountFailed: 'UPDATE_ACCOUNTS_FAILED',
    deleteAccount: 'DELETE_ACCOUNTS',
    deleteAccountSuccess: 'DELETE_ACCOUNTS_SUCCESS',
    deleteAccountFailed: 'DELETE_ACCOUNTS_FAILED',

    fetchOrgSetting:'FETCH_ORG_SETTING',
    fetchOrgSettingSuccess:'FETCH_ORG_SETTING_SUCCESS',
    fetchOrgSettingFailed:'FETCH_ORG_SETTING_FAILED',
    updateOrgSetting:'UPDATE_ORG_SETTING',
    updateOrgSettingSuccess:'UPDATE_ORG_SETTING_SUCCESS',
    updateOrgSettingFailed:'UPDATE_ORG_SETTING_FAILED',
    
}